### ISSUE TITLE
Bakery breaks when PATH contains a folder with more than 260 characters

### ISSUE THREAD

**Issue by nils-a** [cake-build/bakery#132] opened 2021-04-08 21:53 UTC
This came up in https://github.com/cake-build/cake/discussions/3298 :

If `PATH` contains a folder "longer" than 260 characters, bakery breaks on start.
This is fairly easy reproducible by installing the tool `upgrade-assistant` (`dotnet tool install -g upgrade-assistant`)

```text
> Cake.Bakery.exe -verbose --port=8888
... many lines omitted ...
Returning directory "C:/Users/andresen/.dotnet/tools/.store/upgrade-assistant/0.2.220602/upgrade-assistant/0.2.220602/tools/net5.0/any/tools/.store/try-convert/0.7.217901/try-convert/0.7.217901/tools/net5.0/any/runtimes/win/lib/netstandard2.0" from underlying filesystem
Returning directory "C:/Users/andresen/.dotnet/tools/.store/upgrade-assistant/0.2.220602/upgrade-assistant/0.2.220602/tools/net5.0/any/tools/.store/try-convert/0.7.217901/try-convert/0.7.217901/tools/net5.0/any/runtimes/win/lib/netstandard2.0" from underlying filesystem

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at Cake.Core.IO.File..ctor(FilePath path)
   at Cake.Core.IO.Directory.<>c.<GetFiles>b__15_0(FileInfo file)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at Cake.Core.IO.Globbing.GlobVisitor.FindCandidates(DirectoryPath path, MatchableNode node, GlobVisitorContext context, SearchScope option, Boolean includeFiles, Boolean includeDirectories)
   at Cake.Core.IO.Globbing.GlobVisitor.VisitSegment(PathNode node, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.GlobVisitor.VisitRecursiveWildcardSegment(RecursiveWildcardNode node, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.GlobVisitor.VisitSegment(PathNode node, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.GlobVisitor.VisitSegment(PathNode node, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.GlobVisitor.VisitSegment(PathNode node, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.GlobVisitor.VisitSegment(PathNode node, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.GlobVisitor.VisitSegment(PathNode node, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.GlobVisitor.VisitWindowsRoot(WindowsRootNode node, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.GlobVisitor.Walk(GlobNode node, GlobberSettings settings)
   at Cake.Core.IO.Globber.Match(String pattern, GlobberSettings settings)
   at Cake.Core.IO.GlobberExtensions.GetFiles(IGlobber globber, String pattern)
   at Cake.Scripting.CodeGen.CakeScriptGenerator.GetCakePath(DirectoryPath toolPath)
   at Cake.Scripting.CodeGen.CakeScriptGenerator..ctor(IBufferedFileSystem fileSystem, ICakeEnvironment environment, IGlobber globber, ICakeConfiguration configuration, IScriptProcessor processor, IScriptAliasFinder aliasFinder, ICakeAliasGenerator aliasGenerator, ICakeLog log, IEnumerable`1 loadDirectiveProviders)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Cake.Bakery.Composition.Activators.ReflectionActivator.Activate(Container container)
   at Cake.Bakery.Composition.Activators.CachingActivator.Activate(Container container)
   at Cake.Bakery.Composition.ContainerResolver.Resolve(Container container, Type type)
   at Cake.Bakery.Composition.ContainerExtensions.Resolve[T](Container container)
   at Cake.Bakery.Program.Main()
```

**Comment by flcdrg** [comment] 2021-08-16 02:18
Confirmed. Just saw the same thing logged to the Application event log

**Comment by devlead** [comment] 2021-11-25 10:30
@flcdrg is it the same issue now that Bakery has been upgraded to .NET 6?

**Comment by flcdrg** [comment] 2021-11-25 10:35
I've rebuilt my computer since April and don't have the same scenario. If I do I'll let you know

**Comment by devlead** [comment] 2021-11-25 10:43
@flcdrg ok thanks 👍  , then I'll close this, for now as runtime changed and code path doesn't exist anymore since we ship Cake Corer/Common with Bakery now, feel free to re-open or raise a new issue if it occurs again.

**Closed by devlead** 2021-11-25 10:43 UTC
Labels: Bug
